spring.application.name=tp_back


spring.datasource.url=jdbc:mysql://localhost:3306/tp_back?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=qExXkDFVo00KhiIw6HAFrhMbBzxpgPat
jwt.expiration=86400000